# Generated by Django 5.0.3 on 2024-04-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agv',
            fields=[
                ('verhicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('verhicle_model', models.IntegerField(default=' ')),
                ('guidance', models.CharField(default=' ', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=False)),
            ],
        ),
    ]
