# Generated by Django 5.0.3 on 2024-04-18 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agv_identify',
            fields=[
                ('verhicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('verhicle_model', models.IntegerField(default=' ')),
                ('guidance', models.CharField(default=' ', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Agv_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agv_speed', models.FloatField()),
                ('trip_distance', models.FloatField()),
                ('Agv_battery', models.FloatField()),
                ('Agv_distance', models.FloatField()),
                ('previous_node', models.IntegerField()),
                ('next_node', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish'), (2, 'Archive')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Agv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Agv_data', to='agvs.agv_identify')),
            ],
        ),
    ]
