# Generated by Django 5.0.3 on 2024-05-16 18:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agv_identify',
            fields=[
                ('verhicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('verhicle_model', models.IntegerField(default=0)),
                ('guidance', models.CharField(default=' ', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Agv_data',
            fields=[
                ('data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Agv_speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('trip_distance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Agv_battery', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Agv_distance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('previous_node', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('next_node', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('agv_identify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agvs.agv_identify')),
            ],
        ),
    ]
