# Generated by Django 5.0.3 on 2024-04-18 14:04

from django.db import migrations

def create_data(apps, schema_editor):
    Agv_identify = apps.get_model('agvs', 'Agv_identify')
    Agv_identify(verhicle_model='1', guidance="guidance", is_active=True, is_connected= True).save()


class Migration(migrations.Migration):

    dependencies = [
        ('agvs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
