# Generated by Django 5.0.3 on 2024-04-12 01:56

from django.db import migrations

def create_data(apps, schema_editor):
    Agv = apps.get_model('agvs', 'Agv')
    Agv(verhicle_model='1', guidance="guidance", is_active=True, is_connected= True).save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('agvs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
